In [1]:
#Import numpy
import numpy as np
array = np.array([3,33,333]) #Createa rank1 array
print(type(array))

<class 'numpy.ndarray'>


In [2]:
print(array.shape)#shape of np.array

(3,)


In [3]:
print(array[0],array[1],array[2])#accessing elements of np array

3 33 333


In [4]:
array[0] =888 #nparrays are mutable
print(array[0])

888


In [7]:
arr2d = np.array([[11,12,13],[21,22,23]])#create 2d array
print(arr2d) #print the array
print("The shape is 2 rows and 3 columns :", arr2d.shape)
print("Accessing elemenst [0,0],[0,1],[1,0] of nd array: ",arr2d[0,0],arr2d[0,1],arr2d[1,0])

[[11 12 13]
 [21 22 23]]
The shape is 2 rows and 3 columns : (2, 3)
Accessing elemenst [0,0],[0,1],[1,0] of nd array:  11 12 21


In [3]:
import numpy as np
ex1=np.zeros((2,2))#we're asking for a two by two array of zeroes
print(ex1)

[[0. 0.]
 [0. 0.]]


In [4]:
#create a 2by2 array filled with 9.0
ex2 = np.full((2,2),9.0)
print(ex2)

[[9. 9.]
 [9. 9.]]


In [5]:
#create a 2by2 matrix with diagonal 1 and other 0's eye function comes in handy
ex3=np.eye(2,2)
print(ex3)

[[1. 0.]
 [0. 1.]]


In [6]:
#create an array of ones
ex4 = np.ones((1,2))
print(ex4)

[[1. 1.]]


In [7]:
#notice that above matrix is 1X2 array
print(ex4.shape)
#which means we need to access it using two indexes
print()
print(ex4[0,1])

(1, 2)

1.0


In [8]:
#creating an array of random floats between 0 and 1
ex5 = np.random.random((2,2))
print(ex5)

[[0.94269463 0.24963157]
 [0.54337447 0.38739144]]


## Array Indexing

In [11]:
import numpy as np
arr = np.array([[11,12,13,14],[21,22,23,24],[31,32,33,34]])
print(arr)

[[11 12 13 14]
 [21 22 23 24]
 [31 32 33 34]]


In [12]:
#use slicing to get a subarray consisting of first 2 rows X 2columns
slice = arr[:2,1:3]
print(slice)

[[12 13]
 [22 23]]


In [13]:
print("Before :",arr[0,1])
slice[0,0] = 1000
print("After :",arr[0,1])

Before : 12
After : 1000


**In above example we see changing contents of slice sub array also changes contents of parent array as such slice points to 
a part of memory of arr**

In [14]:
#How to create a copy of np array and slice it
slice = np.array(arr[:2,1:3])
print(slice)

[[1000   13]
 [  22   23]]


In [15]:
print("Before :",arr[0,1])
slice[0,0] = 12
print("After :",arr[0,1])

Before : 1000
After : 1000


**This time the contents of parent remain intact as we have made a copy of elements of parent array and made slice point to that copy**

In [19]:
import numpy as np
arr= np.array([[11,12,13,14],[21,22,23,24],[31,32,33,34]])
print(arr)

[[11 12 13 14]
 [21 22 23 24]
 [31 32 33 34]]


In [21]:
rowRank1= arr[1,:]
print(rowRank1,rowRank1.shape)

[21 22 23 24] (4,)


In [22]:
rowRank2 = arr[1:2,:]
print(rowRank2,rowRank2.shape)

[[21 22 23 24]] (1, 4)


**What we see above is that when we used integer index to slice the array we get 1d array and when we used slicing to slice
the same row we got a 2d matrix inspite of it having only one row**

In [24]:
#Lets demonstrate the same thing with colms
print()
colRank1 = arr[:,1]
colRank2 = arr[:,1:2]
print(colRank1,colRank1.shape)
print()
print(colRank2,colRank2.shape)


[12 22 32] (3,)

[[12]
 [22]
 [32]] (3, 1)


**Sometimes its useful use an array of indices to change or access the elements of a larger matrix**

In [26]:
origin = np.array([[11,12,13],[21,22,23],[31,32,33],[41,42,43]])
print(origin,origin.shape)

[[11 12 13]
 [21 22 23]
 [31 32 33]
 [41 42 43]] (4, 3)


In [29]:
#Create an array of indices
col_indices = np.array([0,1,2,0])
print('\nColumn Indices are :',col_indices)
row_indices = np.arange(4)
print('\nRow indices are :',row_indices)


Column Indices are : [0 1 2 0]

Row indices are : [0 1 2 3]


In [31]:
for row,column in zip(row_indices,col_indices):
    print(row," ",column)

0   0
1   1
2   2
3   0


In [33]:
print('Values in array at the indices :',origin[row_indices,col_indices])

Values in array at the indices : [11 22 33 41]


In [34]:
origin[row_indices,col_indices]+=1000
print(origin)

[[1011   12   13]
 [  21 1022   23]
 [  31   32 1033]
 [1041   42   43]]


## Boolean Indexing

In [35]:
an_arr = np.array([[11,12],[21,22],[31,32]])
print(an_arr)

[[11 12]
 [21 22]
 [31 32]]


In [42]:
#Create filter to get a boolean array of all those elements which are greater than 15
filter = (an_arr>15)
print(filter)

[[False False]
 [ True  True]
 [ True  True]]


In [43]:
print(an_arr[filter]) #using filter as indices to get all values are that are true

[21 22 31 32]


In [44]:
an_arr[an_arr>15]

array([21, 22, 31, 32])

In [46]:
an_arr[(an_arr>20) & (an_arr<30)]

array([21, 22])

In [47]:
#asking for even values using bool filters
an_arr[(an_arr%2==0)]

array([12, 22, 32])

In [48]:
an_arr[(an_arr%2==0)]+=1

In [49]:
print(an_arr)

[[11 13]
 [21 23]
 [31 33]]


**Changing the elements using boolean indexing**

## Data Types And Array Operations

In [3]:
import numpy as np
ex1=np.array([11,12])
print(ex1.dtype)

int32


In [4]:
ex2 = np.array([11.0,12.0])
print(ex2.dtype)

float64


In [9]:
ex3 = np.array([11,21],dtype=np.int64)
print(ex3.dtype)

int64


In [11]:
ex4=np.array([11.0,12.0],dtype=np.int64)
print(ex4.dtype)
print()
print(ex4)

int64

[11 12]


In [12]:
ex5 = np.array([11,12],dtype=np.float64)
print(ex5.dtype)
print()
print(ex5)

float64

[11. 12.]


In [14]:
x=np.array([[111,112],[121,122]],dtype=np.int)
y=np.array([[211.1,212.1],[221.1,222.1]],dtype=np.float64)
print(x)
print()
print(y)

[[111 112]
 [121 122]]

[[211.1 212.1]
 [221.1 222.1]]


In [16]:
#add
print(x+y)
print()
print(np.add(x,y))

[[322.1 324.1]
 [342.1 344.1]]

[[322.1 324.1]
 [342.1 344.1]]


In [17]:
#substract
print(x-y)
print()
print(np.subtract(x,y))

[[-100.1 -100.1]
 [-100.1 -100.1]]

[[-100.1 -100.1]
 [-100.1 -100.1]]


In [18]:
print(x*y)
print()
print(np.multiply(x,y))

[[23432.1 23755.2]
 [26753.1 27096.2]]

[[23432.1 23755.2]
 [26753.1 27096.2]]


In [19]:
print(x/y)
print()
print(np.divide(x,y))

[[0.52581715 0.52805281]
 [0.54726368 0.54930212]]

[[0.52581715 0.52805281]
 [0.54726368 0.54930212]]


In [20]:
print(np.sqrt(x))

[[10.53565375 10.58300524]
 [11.         11.04536102]]


In [21]:
print(np.exp(y))

[[4.78151068e+91 1.29974936e+92]
 [1.05319781e+96 2.86288848e+96]]


In [23]:
arr= 10*np.random.randn(2,5)
print(arr)

[[  4.31595757  -7.40955054  -3.02568886 -12.66169298  -5.4825859 ]
 [ -4.95379185   2.23427428   6.2205014   17.72844545  -5.38724372]]


In [25]:
#compute mean of all elements
print(arr.mean())

-0.842137515240249


In [26]:
#mean by row
print(arr.mean(axis=1))

[-4.85271214  3.16843711]


In [27]:
#mean bu columns
print(arr.mean(axis=0))

[-0.31891714 -2.58763813  1.59740627  2.53337624 -5.43491481]


In [29]:
print(arr.sum())

-8.42137515240249


In [31]:
#median by row
print(np.median(arr , axis = 1))

[-5.4825859   2.23427428]


In [32]:
unsorted = np.random.randn(10)
print(unsorted)

[-1.49681838  0.44560294 -1.35083416 -0.76432031 -0.18992175  0.79875081
  1.08849602  0.91029293  1.06847181  0.22412668]


In [33]:
#create copy and sort
sorted = np.array(unsorted)
sorted.sort()
print(sorted)
print()
print(unsorted)

[-1.49681838 -1.35083416 -0.76432031 -0.18992175  0.22412668  0.44560294
  0.79875081  0.91029293  1.06847181  1.08849602]

[-1.49681838  0.44560294 -1.35083416 -0.76432031 -0.18992175  0.79875081
  1.08849602  0.91029293  1.06847181  0.22412668]


In [35]:
array = np.array([1,2,1,4,4,2,1,4,4,2])
print(np.unique(array))

[1 2 4]


In [36]:
s1 = np.array(['desk','chair','bulb'])
s2 = np.array(['lamp','bulb','chair'])
print(s1,s2)

['desk' 'chair' 'bulb'] ['lamp' 'bulb' 'chair']


In [37]:
print(np.intersect1d(s1,s2))

['bulb' 'chair']


In [38]:
print(np.union1d(s1,s2))

['bulb' 'chair' 'desk' 'lamp']


In [40]:
print(np.setdiff1d(s1,s2))

['desk']


In [41]:
print(np.in1d(s1,s2))#which of the elements of s1 are in s2

[False  True  True]


In [1]:
import numpy as np
start = np.zeros((4,3))
print(start)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [2]:
add_rows = np.array([1,0,2])#creating 1X3 array 
print(add_rows)

[1 0 2]


In [3]:
y = start + add_rows #broadcasting adding of two array of different dimensions
print(y)

[[1. 0. 2.]
 [1. 0. 2.]
 [1. 0. 2.]
 [1. 0. 2.]]


In [10]:
add_cols = np.array([[0,1,2,3]])#creating a 4X1 array to add to start using broadcasting via columns
add_cols = np.transpose(add_cols)
print(add_cols)

[[0]
 [1]
 [2]
 [3]]


In [11]:
y = start + add_cols
print(y)

[[0. 0. 0.]
 [1. 1. 1.]
 [2. 2. 2.]
 [3. 3. 3.]]


In [12]:
add_scalar = np.array([1])
print(start + add_scalar)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [16]:
        # determine the dot product of two matrices
        x2d = np.array([[1,1],[1,1]])
        y2d = np.array([[2,2],[3,3]])

        print(x2d.dot(y2d))
        print()
        print(np.dot(x2d, y2d))
        

[[5 5]
 [5 5]]

[[5 5]
 [5 5]]


In [18]:
# determine the inner product of two vectors
a1d = np.array([9 , 8 ])
b1d = np.array([10, 10])

print(a1d.dot(b1d))
print()
print(np.dot(a1d, b1d))

170

170


In [19]:
# dot produce on an array and vector
print(x2d.dot(a1d))
print()
print(np.dot(x2d, a1d))

[17 17]

[17 17]


In [20]:
# sum elements in the array
ex1 = np.array([[11,12],[21,22]])

print(np.sum(ex1))          # add all members

66


In [21]:
print(np.sum(ex1, axis=0))  # columnwise sum

[32 34]


In [22]:
print(np.sum(ex1, axis=1))  # rowwise sum

[23 43]


In [23]:
# random array
x = np.random.randn(8)
x

array([ 2.33774145,  2.16253671, -0.40021725,  1.29485059,  0.09052174,
        0.27809742, -0.85035672,  1.04139765])

In [24]:
# another random array
y = np.random.randn(8)
y

array([-0.24781311, -0.80642157, -0.55953465, -0.19379967,  0.55263095,
       -1.09358115,  1.23055396, -0.21360857])

In [25]:
np.maximum(x,y)

array([ 2.33774145,  2.16253671, -0.40021725,  1.29485059,  0.55263095,
        0.27809742,  1.23055396,  1.04139765])

In [26]:
# grab values from 0 through 19 in an array
arr = np.arange(20)
print(arr)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [27]:
arr.reshape(4,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [28]:
# transpose
ex1 = np.array([[11,12],[21,22]])

ex1.T

array([[11, 21],
       [12, 22]])

In [29]:
x_1 = np.array([1,2,3,4,5])

y_1 = np.array([11,22,33,44,55])

filter = np.array([True, False, True, False, True])

In [30]:
out = np.where(filter, x_1, y_1)
print(out)

[ 1 22  3 44  5]


In [31]:
mat = np.random.rand(5,5)
mat

array([[0.07274938, 0.5946746 , 0.55538785, 0.59653196, 0.32215295],
       [0.6583643 , 0.2380407 , 0.04489282, 0.7521901 , 0.8919774 ],
       [0.78439525, 0.7579061 , 0.00348766, 0.92205056, 0.54397334],
       [0.03413601, 0.85558792, 0.1783851 , 0.23103488, 0.06886849],
       [0.31784313, 0.25099506, 0.24331292, 0.47719273, 0.98514044]])

In [32]:
np.where( mat > 0.5, 1000, -1)

array([[  -1, 1000, 1000, 1000,   -1],
       [1000,   -1,   -1, 1000, 1000],
       [1000, 1000,   -1, 1000, 1000],
       [  -1, 1000,   -1,   -1,   -1],
       [  -1,   -1,   -1,   -1, 1000]])

In [33]:
arr_bools = np.array([ True, False, True, True, False ])

In [34]:
arr_bools.any()

True

In [35]:
arr_bools.all()

False

In [36]:
Y = np.random.normal(size = (1,5))[0]
print(Y)

[-1.07894075 -2.39248809  0.09709748 -0.79755948 -1.02474519]


In [39]:
Z = np.random.randint(low=2,high=50,size=4)
print(Z)

[ 8  7 38 26]


In [40]:
np.random.permutation(Z) #return a new ordering of elements in Z

array([ 7,  8, 38, 26])

In [41]:
np.random.uniform(size=4) #uniform distribution

array([0.83489352, 0.53436201, 0.73156257, 0.5927634 ])

In [42]:
np.random.normal(size=4) #normal distribution

array([ 0.18361986, -1.34222815, -0.18109978, -1.28705963])

## Merging Datasets

In [45]:
K = np.random.randint(low=2,high=50,size=(2,2))
print(K)

print()
M = np.random.randint(low=2,high=50,size=(2,2))
print(M)

[[16 40]
 [27 19]]

[[25 38]
 [38 12]]


In [46]:
np.vstack((K,M))

array([[16, 40],
       [27, 19],
       [25, 38],
       [38, 12]])

In [48]:
np.hstack((K,M))

array([[16, 40, 25, 38],
       [27, 19, 38, 12]])

In [49]:
np.concatenate([K, M], axis = 0)

array([[16, 40],
       [27, 19],
       [25, 38],
       [38, 12]])

In [51]:
np.concatenate([K, M.T], axis = 1)

array([[16, 40, 25, 38],
       [27, 19, 38, 12]])